//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolVendorDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int ToolInternalId { get; set; }
        public string ToolType { get; set; }
        public int ToolQuantity { get; set; }
        public string ToolDesignator { get; set; }
        public string ToolManufacturer { get; set; }
        public double ToolDiameter { get; set; }
        public double ToolFluteLength { get; set; }
        public int ToolFluteNumber { get; set; }
        public string ToolCornerType { get; set; }
        public string ToolMaterial { get; set; }
        public Nullable<int> ToolRake { get; set; }
        public string ToolNotes { get; set; }
        public System.DateTime ToolStockedDate { get; set; }
        public string ToolLink { get; set; }
        public byte[] ToolImage { get; set; }
    }
}
